language: python
python:
 - "3.6"
before_script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - cd docs
  - sphinx-apidoc -e -o . ../diffusion/
  - make html
  - mv _build/html/* .
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PAGES_TOKEN
  keep_history: true
  on:
    branch: rtd
